### PR TITLE
Added base info for reviews app

### PR DESCRIPTION
**Pull request by dyou3968**

### CODE REVIEW

**Review by LeoAndTheTree — COMMENTED** [review]
You also changed the docker-compose ports from 80:8000 to 3000:3000.
Could you revert this change from your commit?

**Comment by dyou3968** [comment]
Ah shoot you're right. Let me change that back.

**Comment by dyou3968** [comment]
Ok I edited it back again. Lmk if there are any issues.

**Comment by LeoAndTheTree** [comment]
The check failed because the model cannot be built right now. For now I will work on this branch until the correct model is implemented.

**Pull request merged**
